config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end
  resources :charges, only: [:new, :create]
  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'downgrade_charge' => 'charges#downgrade'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  has_many :collaborators
  has_many :colaborated_wikis, through: :collaborators, source: :wiki

  enum role: [:standard, :premium, :admin]
  after_initialize { self.role ||= :standard}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  protect_from_forgery with: :exception

rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

private

  def user_not_authorized
    flash[:warning] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  def upgrade_current_user
    current_user.update_attributes(:role => "premium")
  end

  def downgrade_current_user
    current_user.update_attributes(:role => "standard")
    current_user.wikis.update_all(:private => "false")
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    # Amount in cents
    @amount = 1500

    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.name}",
      amount: @amount
    }
  end

  def create
    @amount = 1500
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd'
    )
      upgrade_current_user

    flash[:notice] = "Thanks for all the money, #{current_user.email}!  Feel free to pay me again."
    redirect_to wikis_path

    #rescue block catches and displays errors with a friendly message.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def downgrade
    downgrade_current_user
    redirect_to wikis_path
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find_by_email(params[:email])

    collaborator = @wiki.collaborators.build(user: @user)

    if collaborator.save
      flash[:notice] = "You have added #{@user.email} to your wikki."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "There was an error, please try again."
      redirect_to edit_wiki_path(@wiki)
    end
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = @wiki.collaborators.find(user_id: (params[:id]))

    if @collaborator.destroy
      flash[:notice] = "Collaborator removed from wiki."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "Collaborator could not be removed."
      redirect_to edit_wiki_path(@wiki)
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    @wiki.user = current_user
    authorize @wiki
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.user = current_user
    @wiki.private = params[:wiki][:private]
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
        options = {
            filter_html: true,
            hard_wrap: true,
            link_attributes: { rel: 'nofollow', target: "_blank" },
            space_after_headers: true,
            fenced_code_blocks: true,
        }

        extensions = {
            autolink: true,
            superscript: true,
            disable_indented_code_blocks: true
        }

        renderer = Redcarpet::Render::HTML.new(options)
        markdown = Redcarpet::Markdown.new(renderer, extensions)

        markdown.render(text).html_safe
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <% if current_user.standard? %>
      <h4>Upgrade to a premium account for only 15.00!</h4>
      <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" >
      </script>
   <% elsif current_user.premium? %>
      <h4>Downgrade to a standard account. We're sad to see you go!</h4>
      <h5>Just a warning, all of your private wikis will now become public.</h5>
      <%= link_to "Cancel Premium", downgrade_charge_path, class: "btn btn-danger" %>></script>
   <% end %>
 <% end %>

app/views/collaborators/_collaborator.html.erb
<div class="media">
  <div class="media-body">
    <small>
      <%= collaborator.user.email %>
    </small>
  </div>
</div>

app/views/collaborators/_form.html.erb
<h4>Add a collaborator</h4>
<%= form_for [@wiki, Collaborator.new] do  %>
  <div class="form-group">
      <%= label_tag(:email) %>
      <%= text_field_tag(:email, "Enter an email")%>
  </div>
  <%= submit_tag("Add Collaborator", class: 'btn btn-success') %>
<% end %>
<% if @wiki.collaborators.length != 0 %>
  <div class="form-group">
    <p>Edit Collaborators</p>
    <% @wiki.collaborators.each do |user| %>
      <div class="user">
        <%= user.id %>
            <%= link_to "Delete", wiki_collaborator_path(@wiki, user), method: :delete %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/collaborators/create.html.erb
<h1>Collaborators#create</h1>
<p>Find me in app/views/collaborators/create.html.erb</p>

app/views/collaborators/destroy.html.erb
<h1>Collaborators#destroy</h1>
<p>Find me in app/views/collaborators/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true%>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Bloccipedia", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>
        <div class="pull-right">
          <% if current_user.present? && current_user.standard? %>
            <%= link_to 'Upgrade to Premium', charges_new_path, :class => 'navbar-link' %>
          <% elsif current_user.present? && current_user.premium? %>
            <%= link_to 'Downgrade to Standard', charges_new_path, :class => 'navbar-link' %>
          <% end %>
          <% if user_signed_in? %>
           Signed in as: <strong><%= current_user.email %></strong> User Role: <%= (current_user.role) %>
           <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
           <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
           <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>
      </ul>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
        <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert"><&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Elizabeth Erin Gatewood</h1>
<p></p>

<button class="social-btn"><%= link_to "Follow me", "http://www.facebook.com/erin.worth", class: "social-btn" %></button>

app/views/welcome/index.html.erb
<br>
<h1>Bloccipedia: Social, Markdown Wikis</h1>
 <div class="jumbotron">
   <h1>Create and share Markdown Wikis</h1>
   <p><%= link_to "Sign Up",  new_user_registration_path, :class => 'navbar-link' %></p>
 </div>

 <div class="row">
   <div class="col-md-6">
     <h2>Create as many public wikis as you want!</h2>
     <p><%= link_to "Free Plan" %></p>
   </div>
   <div class="col-md-6">
     <h2>Create both public and private wikis!</h2>
     <p><%= link_to "Premium Plan", class: 'btn btn-primary' %></p>
   </div>
 </div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<p>Guidelines for Editing Wikis</p>
<ul>
  <li>This is may be for free speech but we do not tollerate hate speech</li>
  <li>Don't swear</li>
  <li>Don't troll in the comment section</li>
  <li>Any use of the phrase "Fake News" will get you banned for life</li>
</ul>
</div>
<div class="col-md-8">
      <%= form_for @wiki do |f| %>
        <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
        </div>
        <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
        </div>
        <div class="form-group">
            <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
        <% if current_user.admin? || current_user.premium? %>
          <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
              <%= f.check_box :private %> Private wiki
            <% end %>
          </div>
        <% end %>
      <% end %>

      <% if current_user.admin? || current_user.premium? %>
      <div class = "form-group">
        <%= render 'collaborators/form' %>
      </div>
      <% end %>
    </div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>
<%= link_to "New", new_wiki_path(@wiki), class: 'btn btn-sq-sm btn-success' %>
<% @wikis.each do |wiki| %>
<div class="media">
    <div class="media-body">
        <div class="media-heading">
            <p><%= link_to wiki.title, wiki %><% if wiki.private == true %> <strong> -private </strong> <% end %></p>
        </div>
    </div>
</div>
 <% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>


<div class="row">
  <div class="col-md-4">
    <p>Guidelines for Creating Wikis</p>
    <ul>
      <li>This is may be for free speech but we do not tollerate hate speech</li>
      <li>Don't swear</li>
      <li>Don't troll in the comment section</li>
    </ul>The incessant use of hashtags will get you banned.</li>
  </div>
<div class="col-md-8">
        <%= form_for @wiki do |f| %>
        <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
        </div>
        <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
        </div>
        <div class="form-group">
            <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
        <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
      <% end %>
        <% end %>
    </div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
    <div class="col-md-8">
      <p><%= markdown(@wiki.body) %></p>
    </div>
    <div class="col-md-4">
        <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
        <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    </div>
</div>
<div class="row">
  <div class="col-md-8">
    <p>Collaborators on this wikki include: </p>
    <%= render @wiki.collaborators %>


  </div>
</div>